// endpoints for routing
export const ADMIN_ROUTE = '/admin'
export const AUTHOR_ROUTE = '/author'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const SAVED_ROUTE = '/saved'
export const BREEDS_ROUTE = '/breeds'
export const BREED_INFO_ROUTE = '/breed/:id'
export const BLOG_ROUTE = '/blog'
export const ABOUT_ROUTE = '/about'
